repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: captnseq
  description: CAPTn-seq is an extended Tn-seq pipeline that goes from raw reads to
    gene-gene interaction calls. It has a standard Tn-seq processing mode including
    essentiality scoring, supplemented with genome-wide digenic interaction calling
    (synthetic-lethal and alleviating pairs). It is useful when running High-Throughput
    Transposon Mutagenesis on large mutant collections.
  author: Simon Jeanneau
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gpu
  is_nfcore: true
